version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - nilnesserr
    - staticcheck
    - testifylint
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: QF1008

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
