//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandbox) DeepCopyInto(out *CocoonSandbox) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandbox.
func (in *CocoonSandbox) DeepCopy() *CocoonSandbox {
	if in == nil {
		return nil
	}
	out := new(CocoonSandbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CocoonSandbox) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxAccess) DeepCopyInto(out *CocoonSandboxAccess) {
	*out = *in
	if in.Modes != nil {
		in, out := &in.Modes, &out.Modes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxAccess.
func (in *CocoonSandboxAccess) DeepCopy() *CocoonSandboxAccess {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxEndpoint) DeepCopyInto(out *CocoonSandboxEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxEndpoint.
func (in *CocoonSandboxEndpoint) DeepCopy() *CocoonSandboxEndpoint {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxLifecycle) DeepCopyInto(out *CocoonSandboxLifecycle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxLifecycle.
func (in *CocoonSandboxLifecycle) DeepCopy() *CocoonSandboxLifecycle {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxLifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxList) DeepCopyInto(out *CocoonSandboxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CocoonSandbox, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxList.
func (in *CocoonSandboxList) DeepCopy() *CocoonSandboxList {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CocoonSandboxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxNode) DeepCopyInto(out *CocoonSandboxNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxNode.
func (in *CocoonSandboxNode) DeepCopy() *CocoonSandboxNode {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CocoonSandboxNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxNodeList) DeepCopyInto(out *CocoonSandboxNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CocoonSandboxNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxNodeList.
func (in *CocoonSandboxNodeList) DeepCopy() *CocoonSandboxNodeList {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CocoonSandboxNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxNodePoolStatus) DeepCopyInto(out *CocoonSandboxNodePoolStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxNodePoolStatus.
func (in *CocoonSandboxNodePoolStatus) DeepCopy() *CocoonSandboxNodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxNodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxNodeSpec) DeepCopyInto(out *CocoonSandboxNodeSpec) {
	*out = *in
	if in.APITokenSecretRef != nil {
		in, out := &in.APITokenSecretRef, &out.APITokenSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxNodeSpec.
func (in *CocoonSandboxNodeSpec) DeepCopy() *CocoonSandboxNodeSpec {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxNodeStatus) DeepCopyInto(out *CocoonSandboxNodeStatus) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]CocoonSandboxNodePoolStatus, len(*in))
		copy(*out, *in)
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxNodeStatus.
func (in *CocoonSandboxNodeStatus) DeepCopy() *CocoonSandboxNodeStatus {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxPlacement) DeepCopyInto(out *CocoonSandboxPlacement) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxPlacement.
func (in *CocoonSandboxPlacement) DeepCopy() *CocoonSandboxPlacement {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxPool) DeepCopyInto(out *CocoonSandboxPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxPool.
func (in *CocoonSandboxPool) DeepCopy() *CocoonSandboxPool {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CocoonSandboxPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxPoolList) DeepCopyInto(out *CocoonSandboxPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CocoonSandboxPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxPoolList.
func (in *CocoonSandboxPoolList) DeepCopy() *CocoonSandboxPoolList {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CocoonSandboxPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxPoolNodeStatus) DeepCopyInto(out *CocoonSandboxPoolNodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxPoolNodeStatus.
func (in *CocoonSandboxPoolNodeStatus) DeepCopy() *CocoonSandboxPoolNodeStatus {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxPoolNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxPoolSpec) DeepCopyInto(out *CocoonSandboxPoolSpec) {
	*out = *in
	out.TemplateRef = in.TemplateRef
	if in.UpdateStrategy != nil {
		in, out := &in.UpdateStrategy, &out.UpdateStrategy
		*out = new(CocoonSandboxPoolUpdateStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxPoolSpec.
func (in *CocoonSandboxPoolSpec) DeepCopy() *CocoonSandboxPoolSpec {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxPoolStatus) DeepCopyInto(out *CocoonSandboxPoolStatus) {
	*out = *in
	if in.WarmByNode != nil {
		in, out := &in.WarmByNode, &out.WarmByNode
		*out = make([]CocoonSandboxPoolNodeStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxPoolStatus.
func (in *CocoonSandboxPoolStatus) DeepCopy() *CocoonSandboxPoolStatus {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxPoolUpdateStrategy) DeepCopyInto(out *CocoonSandboxPoolUpdateStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxPoolUpdateStrategy.
func (in *CocoonSandboxPoolUpdateStrategy) DeepCopy() *CocoonSandboxPoolUpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxPoolUpdateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxSpec) DeepCopyInto(out *CocoonSandboxSpec) {
	*out = *in
	out.TemplateRef = in.TemplateRef
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(CocoonSandboxLifecycle)
		**out = **in
	}
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = new(CocoonSandboxAccess)
		(*in).DeepCopyInto(*out)
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(CocoonSandboxPlacement)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxSpec.
func (in *CocoonSandboxSpec) DeepCopy() *CocoonSandboxSpec {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxStatus) DeepCopyInto(out *CocoonSandboxStatus) {
	*out = *in
	if in.Deadline != nil {
		in, out := &in.Deadline, &out.Deadline
		*out = (*in).DeepCopy()
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(CocoonSandboxEndpoint)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxStatus.
func (in *CocoonSandboxStatus) DeepCopy() *CocoonSandboxStatus {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxTemplate) DeepCopyInto(out *CocoonSandboxTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxTemplate.
func (in *CocoonSandboxTemplate) DeepCopy() *CocoonSandboxTemplate {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CocoonSandboxTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxTemplateList) DeepCopyInto(out *CocoonSandboxTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CocoonSandboxTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxTemplateList.
func (in *CocoonSandboxTemplateList) DeepCopy() *CocoonSandboxTemplateList {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CocoonSandboxTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxTemplateSpec) DeepCopyInto(out *CocoonSandboxTemplateSpec) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(TemplateNetworkPolicy)
		**out = **in
	}
	if in.Bootstrap != nil {
		in, out := &in.Bootstrap, &out.Bootstrap
		*out = new(TemplateBootstrap)
		(*in).DeepCopyInto(*out)
	}
	if in.PromotePolicy != nil {
		in, out := &in.PromotePolicy, &out.PromotePolicy
		*out = new(TemplatePromotePolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxTemplateSpec.
func (in *CocoonSandboxTemplateSpec) DeepCopy() *CocoonSandboxTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoonSandboxTemplateStatus) DeepCopyInto(out *CocoonSandboxTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoonSandboxTemplateStatus.
func (in *CocoonSandboxTemplateStatus) DeepCopy() *CocoonSandboxTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(CocoonSandboxTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateBootstrap) DeepCopyInto(out *TemplateBootstrap) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateBootstrap.
func (in *TemplateBootstrap) DeepCopy() *TemplateBootstrap {
	if in == nil {
		return nil
	}
	out := new(TemplateBootstrap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateNetworkPolicy) DeepCopyInto(out *TemplateNetworkPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateNetworkPolicy.
func (in *TemplateNetworkPolicy) DeepCopy() *TemplateNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(TemplateNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplatePromotePolicy) DeepCopyInto(out *TemplatePromotePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplatePromotePolicy.
func (in *TemplatePromotePolicy) DeepCopy() *TemplatePromotePolicy {
	if in == nil {
		return nil
	}
	out := new(TemplatePromotePolicy)
	in.DeepCopyInto(out)
	return out
}
